name: Robot Framework Tests

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Robot Framework and Dependencies
      run: |
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-requests

    - name: Run Robot Framework Tests
      run: robot /home/runner/work/bbc-robot-framework-tests/bbc-robot-framework-tests/robot/tests/
